import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nick Cocks',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ol>
          <li><a href='/art'>Art</a></li>
          <li><a href="/">Home</a></li>
        </ol>
        {children}
      </body>
    </html>
  )
}
